version: '3.8'

services:
  kshop-agent:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload